[CI] Added `es.default.path.conf` config to test cluster launcher
Prevent errors when starting Elasticsearch:

    /usr/share/elasticsearch/bin/elasticsearch -D es.default.path.logs=/tmp
    Failed to configure logging...
    org.elasticsearch.ElasticsearchException: Failed to load logging configuration

Also, removed the `env` matrix, since we now test both 3.x and 4.x versions in the integration tests Rake task.